blog/urls.py
from django.urls import path
from blog import views 

urlpatterns = [
    path('', views.home, name='home' ),
    path('gallery/', views.gallery, name='gallery' ),
    path('contact/', views.contact, name='contact' ),
    path('search/', views.search, name='search' ),
    path("news/", views.blog_index, name="blog_index"),
    path("post/<int:pk>/", views.blog_detail, name="blog_detail"),
    path("category/<category>/", views.blog_category, name="blog_category"),   
]

school/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
] +  static (settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name= models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name
    

class Post(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add= True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField("Category", related_name="posts")
    image= models.ImageField(upload_to="post/")

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey("Post", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.author} on {self.post}"
    
class Contact(models.Model):
    full_name = models.CharField(max_length=60)
    phone_number = models.CharField(max_length=60)
    message = models.TextField()

    def __str__(self):
        return f" {self.full_name} -  {self.phone_number} " 
    
class Gallery(models.Model):
    gallery_image= models.ImageField(upload_to="gallery/")
    created_date = models.DateTimeField(auto_now_add= True)
    modified_date = models.DateTimeField(auto_now=True)

    

blog/forms.py
# forms.py
from django import forms
from blog.models import Comment,Contact

class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Your Name"}
        ),
    )
    body = forms.CharField(
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Leave a comment!"}
        )
    )


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['full_name', 'phone_number', 'message']
        
    widgets = {
        'full_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Full Name'}),
        'phone_number': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Your Phone Number'}),
        'message': forms.Textarea(attrs={'class': 'form-control', 'rows': '4', 'placeholder': 'Your Message'}),
    }

blog/views.py
from django.shortcuts import render, redirect
from blog.models import Category, Comment, Post, Contact,Gallery
from django.http import HttpResponseRedirect
from .forms import ContactForm, CommentForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


#home
def home(request):
    return render (request,'blog/homepage.html')

#blog
def blog_index(request):
    posts = Post.objects.all().order_by("-created_on")
    context = {
        "posts": posts,
    }
    return render(request, "blog/blog_index.html", context)

#blog_category
def blog_category(request,category):
    posts = Post.objects.filter(categories__name__contains = category).order_by("-created_on")
    context = {
        "category":category,
        "posts":posts,
    }
    return render(request, "blog/blog_category.html", context)

#blog_detail
def blog_detail(request,pk):
    post = Post.objects.get(pk=pk)
    #after form
    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data['author'],
                body=form.cleaned_data['body'],
                post=post,
            )
            comment.save()
            return HttpResponseRedirect(request.path_info)
        

    comments = Comment.objects.filter(post=post)

    #before form
    context = {
        "post":post,
        "comments":comments,  
        #after form
        'form':CommentForm(),
    }
    return render(request, "blog/blog_detail.html",context)

#contact
def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            # Add a success message
            messages.success(request, 'Your message was sent successfully!')
            
            # Create a new empty form
            form = ContactForm()

            return render(request, 'blog/contact.html', {'form': form})
    else:
        form = ContactForm()

    return render(request, 'blog/contact.html', {'form': form})


# search function


def search(request):
    query=request.GET['query']

    if len(query)>78:
        myPosts=Post.objects.none()
    else:
        myPostsTitle= Post.objects.filter(title__icontains=query)
        myPostsContent =Post.objects.filter(body__icontains=query)
        myPosts=  myPostsTitle.union(myPostsContent)

    '''
    if myPosts.count()==0:
        messages.warning(request, "No search results found. Please refine your query.")
    '''
    
    params={'allPosts': myPosts, 'query': query}

    return render(request, 'blog/search.html', params)

#gallery
def gallery(request):
    images = Gallery.objects.all().order_by("-created_date")

    # Paginate the list of images
    paginator = Paginator(images, 9)  # Change 9 to the desired number of images per page

    # Get the current page number from the request, default to 1
    page_number = request.GET.get('page', 1)

    try:
        # Retrieve the images for the current page
        images_page = paginator.page(page_number)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page
        images_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results
        images_page = paginator.page(paginator.num_pages)
    context={
        'images_page':images_page
    }
    
    return render (request,'blog/gallery.html',context)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> YouMe School </title>
   <!-- {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load bootstrap_icons %}
   -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300&display=swap" rel="stylesheet">
</head>
<body>

    {% include "blog/navbar.html" %}
    


    {% block page_title %}

    {% endblock page_title %}

    {% block page_content %}
        
    {% endblock page_content %}

    {% include "blog/footer.html" %}


    <script 
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/blog_category.html
{% extends "blog/blog_index.html" %}



{{category}}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}

{% block page_content %}
<div class="container my-5">
    <small class="my-5">
        {{ post.created_on.date }} | Categories:
        {% for category in post.categories.all %}
        <a href="{% url 'blog_category' category.name %}">
            {{ category.name }}
        </a>
        {% endfor %}
    </small>
    <br>
    <img src="/media/{{post.image}}" class="img-fluid" alt="...">
    <p>{{ post.body | linebreaks }}</p>

    <h3>Leave a comment:</h3>
    <form method="post" class="form col-sm-12 col-lg-5 mb-4">
        {% csrf_token %}
        <!-- csrf_token provides security and renders the body and author fields of 
                the form, followed by a submit button.
            -->
        <div class="mb-4">
            {{ form.author }}
        
        </div>
        
        <div class="mb-4">
            {{ form.body }}
        </div>
        <button type="submit" class="btn btn-outline-primary  w-25 mx"> send </button>
    </form>

    <h3>Comments:</h3>

    {% for comment in comments %}
    <div class="card text-bg-light mb-3" style="max-width: 18rem;">
        <div class="card-header"> On {{ comment.created_on.date }} <b>{{ comment.author }}</b> wrote:
            <p class="card-text">{{ comment.body | linebreaks }}</p>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock page_content %}

blog/templates/blog/blog_index.html
{% extends "blog/base.html" %}


{% block page_content %}
<div class="text-center my-5">
    <h1 data-aos="fade-up" data-aos-offset="200">School <span class="text-primary">Blogs</span></h1>
    <hr class="w-25 m-auto" />
</div>



<!-- using bootsrap card -->

<div class="row mt-3">
    {% for post in posts %}
    <div class="col-sm-12 col-md-6 col-lg-4 mb-4">

        <div class="card">

            <img src="/media/{{post.image}}" class="card-img-top" style="height: 250px;" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{post.title}}</h5>
                <small class="mb-5">
                    {{ post.created_on.date }} | Categories:
                    {% for category in post.categories.all %}
                    <a href="{% url 'blog_category' category.name %}">
                        {{ category.name }}
                    </a>
                    {% endfor %}
                </small>
                <p class="card-text mt-4">{{post.body | slice:"70"}}....</p>
                <a href="{% url 'blog_detail' post.pk %}" class="btn btn-primary">
                    Read More
                </a>
            </div>

        </div>

    </div>
    {% endfor%}
</div>





{% endblock page_content %}

blog/templates/blog/calendar.html
<!-- calender image -->

<!-- row, 2 col(previous & upcoming  event)   -->


<!-- calendar_page.html -->
{% extends 'blog/base.html' %}

{% block page_title %}
 hjgh
{% endblock page_title %}


{% block page_content %}
<div class="container d-flex flex-column justify-content-center align-items-center m-5">
    <div class="text-center my-5">
      <h1>Major <span class="text-primary"> Events </span></h1>
      <hr class="w-25 m-auto " />
    </div>
  <div class="row row-striped">
    <div class="col-2 text-right">
      <h1 class="display-4"><span class="badge badge-secondary">23</span></h1>
      <h2>OCT</h2>
    </div>
    <div class="col-10">
      <h3 class="text-uppercase"><strong>Ice Cream Social</strong></h3>
      <ul class="list-inline">
          <li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i> Monday</li>
        <li class="list-inline-item"><i class="fa fa-clock-o" aria-hidden="true"></i> 12:30 PM - 2:00 PM</li>
        <li class="list-inline-item"><i class="fa fa-location-arrow" aria-hidden="true"></i> Cafe</li>
      </ul>
      <p>Lorem ipsum dolsit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
  </div>
  <div class="row row-striped">
    <div class="col-2 text-right">
      <h1 class="display-4"><span class="badge badge-secondary">27</span></h1>
      <h2>OCT</h2>
    </div>
    <div class="col-10">
      <h3 class="text-uppercase"><strong>Operations Meeting</strong></h3>
      <ul class="list-inline">
          <li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i> Friday</li>
        <li class="list-inline-item"><i class="fa fa-clock-o" aria-hidden="true"></i> 2:30 PM - 4:00 PM</li>
        <li class="list-inline-item"><i class="fa fa-location-arrow" aria-hidden="true"></i> Room 4019</li>
      </ul>
      <p>Lorem ipsum dolsit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
  </div>
</div>
   
{% endblock page_content %}

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% load static %}



{% block page_content %}
<div class="container d-flex flex-column justify-content-center align-items-center my-5">
  <div class="text-center">
    <h1>Contact <span class="text-primary"> us </span></h1>
    <hr class="w-25 m-auto " />
  </div>

  {% if messages %}
  <div class="alert alert-success" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
  </div>
  {% endif %}

  <form method="post" action="{% url 'contact' %}" class="form col-sm-12 col-lg-5 mb-4">
    {% csrf_token %}

    <div class="mb-4">
      <label for="id_full_name" class="form-label">Name</label>
      <input type="text" name="full_name" class="form-control" id="id_full_name" placeholder="Full Name" required>
    </div>

    <div class="mb-4">
      <label for="id_email" class="form-label">Phone Number</label>
      <input type="text" name="phone_number" class="form-control" id="id_phone_number" placeholder="Your Phone Number"
        required>
    </div>

    <div class="mb-4">
      <label for="id_message" class="form-label">Message</label>
      <textarea name="message" class="form-control" id="id_message" rows="4" placeholder="Your Message"
        required></textarea>
    </div>

    <button type="submit" class="btn btn-outline-primary w-25 mx">Send</button>
  </form>
</div>


{% endblock page_content %}

blog/templates/blog/footer.html
<!-- Footer Start -->
<footer class="container-fluid text-center text-lg-start text-muted bg_footer">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Get connected with us on social networks:</span>
        </div>
        <!-- Left -->
  
        <!-- Right -->
        <div class="text">
            <a href="https://www.facebook.com/youmekht/" class="me-4 text-reset">
                <i class="bi bi-facebook"></i>
            </a>
            
            <a href="https://www.youtube.com/@youmenepal5003" class="me-4 text-reset">
                <i class="bi bi-youtube"></i>
            </a>
            <a href="https://www.instagram.com/youme_nepal/" class="me-4 text-reset">
                <i class="bi bi-instagram"></i>
            </a>
            <a href="https://np.linkedin.com/" class="me-4 text-reset">
                <i class="bi bi-linkedin"></i>
            </a>
        </div>
        <!-- Right -->
    </section>
    <!-- end of Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="container-fluid">
        <div class="container-fluid text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        <i class="fas fa-gem me-3"></i>Developed By
                    </h6>
                    <p>
                        YouMe Khotang  IT Club
                    </p>
                </div>
                <!-- Grid column -->
  
                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Courses
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Coding</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Music</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Sport</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Dance</a>
                    </p>
                </div>
                <!-- Grid column -->
  
                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Useful links
                    </h6>
                    <p>
                        <a href="https://www.facebook.com/youmekht/" class="text-reset">Facebook</a>
                    </p>
                    <p>
                        <a href="https://www.youtube.com/@youmenepal5003" class="text-reset">Youtube</a>
                    </p>
                    <p>
                        <a href="https://www.instagram.com/youme_nepal/" class="text-reset">Instagram</a>
                    </p>
                    <p>
                        <a href="https://np.linkedin.com/" class="text-reset">Linkedin</a>
                    </p>
                </div>
                <!-- Grid column -->
  
                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                    <p><i class="fas fa-home me-3"></i>Khotang,Nepal</p>
                    <p>
                        <i class="fas fa-envelope me-3"></i>
                        info@youmenepal.org
                    </p>
                    <p><i class="fas fa-phone me-3"></i> 9841070026 </p>
                    <p><i class="fas fa-print me-3"></i>  9869808718 </p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © Copyright:
        <a class="text-reset fw-bold" href="#"> YouMe IT Club </a>
    </div>
    </footer>

blog/templates/blog/gallery.html
{% extends 'blog/base.html' %}

{% load static %}

{% block page_title %}

{% endblock page_title %}

{% block page_content %}

<!-- gallery  start-->
<section class="gallery my-5 h-100" id="/gallery">
    <div class="container-fluid">
        <div class="text-center my-5">
            <h1 data-aos="fade-up" data-aos-offset="200">School <span class="text-primary">Gallery</span></h1>
            <hr class="w-25 m-auto" />
        </div>
        <div class="row mb-4">
            {% for photo in images_page %}
            <div class="col-lg-4  mb-4">
                <img src="/media/{{photo.gallery_image}}" class="w-100 h-100 shadow-1-strong rounded mb-4"
                    alt="image" />
            </div>
            {% endfor %}
        </div>
        <!-- Pagination controls -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if images_page.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ images_page.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}
                {% for num in images_page.paginator.page_range %}
                <li class="page-item {% if num == images_page.number %}active{% endif %}">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endfor %}
                {% if images_page.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ images_page.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>

    </div>
</section>
<!-- gallery end -->

{% endblock page_content %}

blog/templates/blog/homepage.html
{% extends 'blog/base.html'%}
{% load static %}

{% block page_content %}

<!--carousel start-->
<div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="10000">
            <img src="{% static 'images/banner1.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="2000">
            <img src="{% static 'images/banner2.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/gallery2.jpeg' %}" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<!-- carousel end-->

<!-- About Start-->
<section class="about my-5" id="about">
    <div class="container-fluid">
        <div class="text-center my-5">
            <!-- data-aos for animation  and offset value for how fast we wanna render-->
            <h1 data-aos="fade-up" data-aos-offset="200"> About <span class="text-primary">us</span></h1>
            <hr class="w-25 m-auto " />
        </div>
        <!-- bootstrap grid-->
        <div class="row">
            <!-- left side-->
            <div class="col-sm-12 col-md-6 col-lg-6" data-aos="fade-right" data-aos-offset="250">
                <h1> What do you <span class="text-primary"> want to know?</span></h1>
                <p> 
                    YouMe School Khotang is an non-profitable organization that provides educational support to help pave the way for the future of children in khotang, Nepal.This organization was founded by its representative, Sharad Rai, when he was a university student with the thoughts of ``I want to open up a future for the children of my home country of Nepal!'' and ``I want to give back to my home country that has raised me!''
                </p>
                <!-- button-->

                <!-- adding accordion-->
                <div class="accordion" id="accordionExample">
                    <div class="accordion-item">
                        <h2 class="accordion-header">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Qualified and Enthusiastic Teachers
                            </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse show"
                            data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <strong>Our YouMe school Khotang</strong> 
                                 prides itself on a team of qualified teachers hailing from various regions of Nepal. Their diverse backgrounds enrich the learning experience for students, offering unique perspectives and insights.
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                Well-Equipped Teaching Materials
                            </button>
                        </h2>
                        <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <strong>With access to a wide array of materials,</strong> 
                                 students are encouraged to explore, experiment, and discover. Whether it's science experiments, art projects, or multimedia presentations, our classrooms are equipped to facilitate hands-on learning experiences.
                            </div>
                        </div>
                    </div>
                   
                </div>

            </div>
            <!-- Right side -->
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-12 m-auto text-right">
                
                <iframe class="rounded" width="100%" height="400px" src="https://www.youtube.com/embed/-mnnB9QZxcA?si=JSutIwZdckhJpoi4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

            </div>
        </div>

    </div>
</section>
<!-- About End-->

<!-- Our Services Start-->
<section class="services my-5 bg-light" id="services">
    <div class="container-fluid d-flex flex-column">
        <div class="text-center my-5">
            <h1 data-aos="fade-up" data-aos-offset="200">Our <span class="text-primary">Courses</span></h1>
            <hr class="w-25 m-auto" />
        </div>
        <!-- to add cards-->
        <div class="row">
            <div class="col-sm-12 col-md-4 col-lg-4 col-12 mb-4" data-aos="flip-down" data-aos-offset="300">
                <div class="card ">
                    <img src="{% static 'images/lab.jpg' %}" class="card-img-top rounded shadow-lg" alt="IT" height="300">
                    <div class="card-img-overlay">
                        <h5 class="card-title">Computer Programming</h5>
                        <p class="card-text">
                            We offer a wide range of programming courses that include HTml ,CSS,Python and
                            Bootstrap.
                        </p>

                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-4 col-12 mb-4" data-aos="flip-up" data-aos-offset="300">
                <div class="card">
                    <img src="{% static 'images/music.jpg' %}" class="card-img-top shadow-lg rounded" alt="music"
                        height="300">
                    <div class="card-img-overlay">
                        <h5 class="card-title">Arts & Music</h5>
                        <p class="card-text">
                            We offer a wide range of arts and music courses that include paper crafts, guitar and
                            keyboard.
                        </p>

                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-4 col-12 mb-4 " data-aos="flip-down" data-aos-offset="300">
                <div class="card">
                    <img src="{% static 'images/sport.jpg' %}" class="card-img-top rounded shadow-lg" alt="sport"
                        height="300">
                    <div class="card-img-overlay">
                        <h5 class="card-title">Sports</h5>
                        <p class="card-text">
                            We offer a wide range of sports courses that include football,volleyball, tennis and
                            table tennis.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Our Serives End-->

<!-- Founder  start-->
<div class="container shadow mt-5">
    <div class="text-center">
        <h1>Our <span class="text-primary"> Founder </span></h1>
        <hr class="w-25 m-auto " />
    </div>
    <div class="row d-flex justify-content-center align-items-center">
        <div class="col-sm-12 col-md-4 border-bottom p-4 d-flex justify-content-center align-items-center">
            <img src="{% static 'images/sarad sir.jpg'%}" class="border border-5 rounded-circle" alt="User" height="250"
                width="250">
        </div>
        <div class="col-sm-12 col-md-7 p-4">
            <p> 
                Namaste. My name is Sharad Rai and I am the representative of the NPO YouMe Nepal. Although I currently live in Japan and worked for a Japanese company, I was born and raised in Nepal.I want the children of YouMe School to give back to the country by becoming leaders in various fields.I want each and every one to demonstrate their abilities and think about their own lives.That's why I created a school. 
            </p>
            <h3> ~ Sarad  Rai</h3>
        </div>
    </div>
</div>
<!-- Founder end -->

<!-- contact us start-->
<section class="contact my-5" id="contact">
    <div class="container">
        <div class="text-center my-5">
            <h1>Contact <span class="text-primary"> us </span></h1>
            <hr class="w-25 m-auto " />
        </div>
        <div class="row justify-content-between">
            <form method="post" action="{% url 'contact' %}" class="form col-sm-12 col-lg-5 mb-4">
                {% csrf_token %}

                <div class="mb-4">
                    <label for="id_full_name" class="form-label">Name</label>
                    <input type="text" name="full_name" class="form-control" id="id_full_name" placeholder="Full Name"
                        required>
                </div>

                <div class="mb-4">
                    <label for="id_email" class="form-label">Phone Number</label>
                    <input type="text" name="phone_number" class="form-control" id="id_phone_number"
                        placeholder="Your Phone Number" required>
                </div>

                <div class="mb-4">
                    <label for="id_message" class="form-label">Message</label>
                    <textarea name="message" class="form-control" id="id_message" rows="4" placeholder="Your Message"
                        required></textarea>
                </div>

                <button type="submit" class="btn btn-outline-primary w-25 mx">Send</button>
            </form>
            <div class="map col-sm-12 col-lg-6">
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3549.1055164090517!2d86.58976437368409!3d27.184420248364567!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39e9359c906babcf%3A0x2c0155dd0f00ce43!2sYouMe%20School!5e0!3m2!1sen!2snp!4v1709172129076!5m2!1sen!2snp"
                    style="border:0;" allowfullscreen="" loading="lazy" class="w-100 h-100 p-2"
                    referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </div>
</section>
<!-- contact end-->

{% endblock page_content %}